// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CerrarInstalador() {
  return window['go']['main']['App']['CerrarInstalador']();
}

export function EjecutarAppIniciada(arg1) {
  return window['go']['main']['App']['EjecutarAppIniciada'](arg1);
}

export function IniciarInstalacion(arg1, arg2) {
  return window['go']['main']['App']['IniciarInstalacion'](arg1, arg2);
}

export function ObtenerRutaDefecto() {
  return window['go']['main']['App']['ObtenerRutaDefecto']();
}
