// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CerrarInstalador():Promise<void>;

export function EjecutarAppIniciada(arg1:string):Promise<void>;

export function IniciarInstalacion(arg1:string,arg2:boolean):Promise<void>;

export function ObtenerRutaDefecto():Promise<string>;
