// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {biometric} from '../models';
import {ac} from '../models';
import {network} from '../models';
import {storage} from '../models';

export function AplicarDeltaAC(arg1:string):Promise<Record<string, any>>;

export function CapturarHuella(arg1:string):Promise<biometric.ResultadoHuella>;

export function ConsultarAC(arg1:string,arg2:number):Promise<ac.Ciudadano>;

export function ForzarVerificacionRed():Promise<network.EstadoRed>;

export function GuardarSolicitud(arg1:storage.SolicitudCertificacion):Promise<string>;

export function ListarSolicitudesPendientes():Promise<Array<storage.SolicitudCertificacion>>;

export function ObtenerEstadisticasAC():Promise<Record<string, any>>;

export function ObtenerEstadoRed():Promise<network.EstadoRed>;

export function ObtenerEstadoSensor():Promise<biometric.EstadoSensor>;

export function SimularSincronizacionLote():Promise<Record<string, any>>;
