// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AplicarDeltaAC(arg1) {
  return window['go']['main']['App']['AplicarDeltaAC'](arg1);
}

export function CapturarHuella(arg1) {
  return window['go']['main']['App']['CapturarHuella'](arg1);
}

export function ConsultarAC(arg1, arg2) {
  return window['go']['main']['App']['ConsultarAC'](arg1, arg2);
}

export function ForzarVerificacionRed() {
  return window['go']['main']['App']['ForzarVerificacionRed']();
}

export function GuardarSolicitud(arg1) {
  return window['go']['main']['App']['GuardarSolicitud'](arg1);
}

export function ListarSolicitudesPendientes() {
  return window['go']['main']['App']['ListarSolicitudesPendientes']();
}

export function ObtenerEstadisticasAC() {
  return window['go']['main']['App']['ObtenerEstadisticasAC']();
}

export function ObtenerEstadoRed() {
  return window['go']['main']['App']['ObtenerEstadoRed']();
}

export function ObtenerEstadoSensor() {
  return window['go']['main']['App']['ObtenerEstadoSensor']();
}

export function SimularSincronizacionLote() {
  return window['go']['main']['App']['SimularSincronizacionLote']();
}
